/** @type {import('tailwindcss').Config} */
export default {
    content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                additional1: [
                    "var(--color-additional1-100)",
                    "var(--color-additional1-200)",
                    "var(--color-additional1-300)",
                    "var(--color-additional1-400)",
                    "var(--color-additional1-500)",
                    "var(--color-additional1-600)",
                    "var(--color-additional1-700)",
                ],
                additional2: [
                    "var(--color-additional2-100)",
                    "var(--color-additional2-200)",
                    "var(--color-additional2-300)",
                    "var(--color-additional2-400)",
                    "var(--color-additional2-500)",
                    "var(--color-additional2-600)",
                    "var(--color-additional2-700)",
                ],
                additional3: [
                    "var(--color-additional3-100)",
                    "var(--color-additional3-200)",
                    "var(--color-additional3-300)",
                    "var(--color-additional3-400)",
                    "var(--color-additional3-500)",
                    "var(--color-additional3-600)",
                    "var(--color-additional3-700)",
                ],
                additional4: [
                    "var(--color-additional4-100)",
                    "var(--color-additional4-200)",
                    "var(--color-additional4-300)",
                    "var(--color-additional4-400)",
                    "var(--color-additional4-500)",
                    "var(--color-additional4-600)",
                    "var(--color-additional4-700)",
                ],
                additional5: [
                    "var(--color-additional5-100)",
                    "var(--color-additional5-200)",
                    "var(--color-additional5-300)",
                    "var(--color-additional5-400)",
                    "var(--color-additional5-500)",
                    "var(--color-additional5-600)",
                    "var(--color-additional5-700)",
                ],
                additional6: [
                    "var(--color-additional6-100)",
                    "var(--color-additional6-200)",
                    "var(--color-additional6-300)",
                    "var(--color-additional6-400)",
                    "var(--color-additional6-500)",
                    "var(--color-additional6-600)",
                    "var(--color-additional6-700)",
                ],
                additional7: [
                    "var(--color-additional7-100)",
                    "var(--color-additional7-200)",
                    "var(--color-additional7-300)",
                    "var(--color-additional7-400)",
                    "var(--color-additional7-500)",
                    "var(--color-additional7-600)",
                    "var(--color-additional7-700)",
                ],
                additional8: [
                    "var(--color-additional8-100)",
                    "var(--color-additional8-200)",
                    "var(--color-additional8-300)",
                    "var(--color-additional8-400)",
                    "var(--color-additional8-500)",
                    "var(--color-additional8-600)",
                    "var(--color-additional8-700)",
                ],
                danger: [
                    "var(--color-danger-100)",
                    "var(--color-danger-200)",
                    "var(--color-danger-300)",
                    "var(--color-danger-400)",
                    "var(--color-danger-500)",
                    "var(--color-danger-600)",
                    "var(--color-danger-700)",
                ],
                primary: [
                    "var(--color-primary-100)",
                    "var(--color-primary-200)",
                    "var(--color-primary-300)",
                    "var(--color-primary-400)",
                    "var(--color-primary-500)",
                    "var(--color-primary-600)",
                    "var(--color-primary-700)",
                ],
                success: [
                    "var(--color-success-100)",
                    "var(--color-success-200)",
                    "var(--color-success-300)",
                    "var(--color-success-400)",
                    "var(--color-success-500)",
                    "var(--color-success-600)",
                    "var(--color-success-700)",
                ],
                warning: [
                    "var(--color-warning-100)",
                    "var(--color-warning-200)",
                    "var(--color-warning-300)",
                    "var(--color-warning-400)",
                    "var(--color-warning-500)",
                    "var(--color-warning-600)",
                    "var(--color-warning-700)",
                ],
                neutral: [
                    "var(--color-neutral-0)",
                    "var(--color-neutral-100)",
                    "var(--color-neutral-200)",
                    "var(--color-neutral-300)",
                    "var(--color-neutral-400)",
                    "var(--color-neutral-500)",
                    "var(--color-neutral-600)",
                    "var(--color-neutral-700)",
                    "var(--color-neutral-800)",
                    "var(--color-neutral-900)",
                    "var(--color-neutral-1000)",
                ],
            },
        },
    },
    plugins: [],
    corePlugins: {
        // preflight: false,
    },
    important: "#root",
};
